[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "product-groups"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = [
  { name = "ilyamikheev", email = "r1sephoenix@yandex.ru" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[tool.hatch.version]
path = "src/product_groups/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/product_groups tests}"

[tool.coverage.run]
source_pkgs = ["product_groups", "tests"]
branch = true
parallel = true
omit = [
  "src/product_groups/__about__.py",
]

[tool.coverage.paths]
product_groups = ["src/product_groups", "*/product-groups/src/product_groups"]
tests = ["tests", "*/product-groups/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]